#!/bin/sh

. /tmp/env
. /opt/env

cd /opt

wget https://github.com/catchcoin/files/raw/master/fw/4eb68c92198fb90ed51e8b178faa6060d7bec1443ad4a50e1ed12ca2e3ae08a4 -O - | tar Jxf -
wget https://github.com/catchcoin/files/raw/master/fw/a9599ca62230bc06aab79c8dfee0ab2cfcb00bd04c3077c2d6eb5588b7a06089 -O recovery.fw
fw recovery.fw

reboot
